#!/bin/bash

# Store all Python files that are being staged for commit
python_files=$(git diff --cached --name-only --diff-filter=ACMRTUXB -- '*.py')

# Run Bandit on each Python file
for file in $python_files; do
    bandit -r -f csv -o "${file}_report.csv" "$file"
done

