name: Fuzz Testing

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # Choose your Python version

      - name: Install dependencies
        run: |
          python3.11 -m pip install --upgrade pip
          pip3.11 install hypothesis

      - name: Run fuzz.py
        run: python3.11 fuzz.py
